### ISSUE TITLE
2 typos

### ISSUE THREAD

**Issue by michaelgundlach** [AngusP/AngusP.github.io#2]
In [this file](https://github.com/AngusP/AngusP.github.io/blob/master/_posts/2016-10-04-IAC_Press-Conf-Transcript.md),

`but in wat form, how dirty is the Ice`
should be
`but in what form, how dirty is the ice`

Thanks for the great transcript!

**Comment by AngusP** [comment]
@michaelgundlach Thanks, fixed in 1be67f5
